---
language: perl

os:
  - linux
  # - osx

# services:
#   - docker

perl:
  - "5.26-extras"
  - "5.24-extras"
  - "5.22-extras"

sudo: false

install:
  # - sudo apt-get update -q
  # - sudo apt-get install -y liburi-perl
  - cpanm -qin --skip-satisfied $(cat requrements.txt)

script:
  - perl -MO=Lint ./gedcom
  - perl -c -Mwarnings::unused ./gedcom

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log
